version: "3.7"
services:
  app:
    image: bdtapp:latest
    env_file: .env
    build:
      # 2.1.Specify the root path
      context: .
      # 2.2.From the root path defined in context, here we define where the Dockerfile resides
      dockerfile: Dockerfile
    
        
 # nginx:
 #   build:
 #     context: ./nginx
 #     dockerfile: ./nginx.Dockerfile
    # 2.3.Like depends_on, links expresses dependency among services. In our case, app and nginx
 #   links:
 #     - app
    # 2.4.Binds port 80 for public connections
    ports:
      - "80:80"
      - "443:443"

 # command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
